version: 2.1

jobs:
  build:
    docker:
      - image: cimg/cmake:3.25
    steps:
      - checkout
      - run:
          name: Build with CMake
          command: |
            cmake .
            make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build